# Generated by Django 4.1.7 on 2023-03-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcod',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره تماس'),
        ),
    ]
