# Generated by Django 4.1.7 on 2023-03-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imag',
            field=models.ImageField(upload_to='products/media/imag/%Y/%m/%d/', verbose_name='عکس'),
        ),
    ]
