# Generated by Django 4.1.7 on 2023-03-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imag',
            field=models.ImageField(upload_to='products/', verbose_name='عکس'),
        ),
    ]
