# Generated by Django 4.1.7 on 2023-04-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('price', 'quantity'), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='order',
            name='trackingcode',
            field=models.PositiveIntegerField(default=0, verbose_name='کد پیگیری'),
        ),
    ]
